import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Hedearorg from "./components/hedear/hedearorg";
import Foother from "./components/foother/foother";
import { ContextProvider } from "./components/context/context";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const hamid = Geist_Mono({
  variable: "--font-iran",
  subsets: ['latin'], // ← این خط خیلی مهمه
  preload: true,     
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${hamid.variable} antialiased **:font-iran max-w-screen-2xl  mx-auto py-44 bg-[#333333]   `}
      >
        <ContextProvider>
          <Hedearorg />
          {children}
          <Foother />
        </ContextProvider>
      </body>
    </html>
  );
}
